<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => 'Адрес',
    'Age' => 'Возраст',
    'Base' => 'Базовая',
    'Choose your language' => '',
    'Company' => 'Групповая',
    'Create Member' => 'Создать участника',
    'Create Party' => 'Создать встречу',
    'Create Place' => 'Создать место',
    'Create Price' => 'Создать цену',
    'Created At' => 'Создан От',
    'Description' => 'Описание',
    'Dob' => 'День рождения',
    'Email' => '',
    'English' => 'Английский',
    'ID' => '',
    'Photo' => 'Фото',
    'Is Default' => 'По умолчанию',
    'Landing' => 'Лэндинг',
    'Map'   => 'Карта',
    'Member ID' => '',
    'Members' => 'Участники',
    'Name' => 'Имя',
    'Paid' => 'Оплачено',
    'Parties' => 'Встречи',
    'Party ID' => '',
    'Phone' => 'Телефон',
    'Place ID' => '',
    'Places' => 'Места',
    'Please contact us if you think this is a server error. Thank you.' => '',
    'Price ID' => '',
    'Prices' => 'Расценки',
    'Repeat' => 'Повторная',
    'Resume' => 'Продолжить',
    'Russian' => 'Русский',
    'Sex' => 'Пол',
    'The requested page does not exist.' => '',
    'Timestamp' => 'Время',
    'Update Member: {0}' => 'Обновить участника: {0}',
    'Update Party: {0}' => 'Обновить встречу: {0}',
    'Update Place: {0}' => 'Обновить место: {0}',
    'Update Price: {0}' => 'Обновить стоимость: {0}',
    'Updated At' => 'Обновлен От',
    'User ID' => '',
    'Visited' => 'Посещено',
];
