<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Admin' => 'Администратор',
    'Asks' => 'Заявки',
    'Control' => 'Контроль',
    'Confirmed' => 'Записан',
    'Create Ask' => 'Создать заявку',
    'ID' => '',
    'Is Blocked' => 'Блокировано',
    'Panel' => 'Панель',
    'Party' => 'Встреча',
    'Place' => 'Место',
    'Price' => 'Расценки',
    'Processed' => 'Обработана',
    'Update Ask: {0}' => 'Обновить заявку: {0}',
    'User' => 'Аккаунт',
    'Address' => 'Адрес',
    'Admin Panel' => 'Панель Администратора',
    'Age' => 'Возраст',
    'Base' => 'Базовая',
    'Female' => 'Женский',
    'Cannot delete default!' => 'Нельзя удалить элемент по умолчанию!',
    'Company' => 'Групповая',
    'Comment' => 'Комментарий',
    'Closed' => 'Закрыто',
    'Create Member' => 'Создать участника',
    'Create Party' => 'Создать встречу',
    'Create Place' => 'Создать место',
    'Create Price' => 'Создать расценки',
    'Created At' => 'Создано',
    'Description' => 'Описание',
    'Dob' => 'День рождения',
    'English' => 'Английский',
    'Is Default' => 'По умолчанию',
    'Landing' => 'Лэндинг',
    'Male' => 'Мужской',
    'Manager' => 'Менеджер',
    'Map' => 'Карта',
    'Max Members' => 'Предел участников',
    'Member' => 'Участник',
    'Members' => 'Участники',
    'Name' => 'Имя',
    'Operator' => 'Оператор',
    'Paid' => 'Оплачено',
    'Party Name' => 'Название',
    'Place Name' => 'Название',
    'Parties' => 'Встречи',
    'Phone' => 'Телефон',
    'Photo' => 'Фото',
    'Places' => 'Места',
    'Prices' => 'Расценки',
    'Remember Me' => 'Запомнить',
    'Repeat' => 'Повторная',
    'Member Resume' => 'О себе',
    'Russian' => 'Русский',
    'Select asked party' => 'Выберите запрашиваемую встречу',
    'Select ask member' => 'Выберите участника заявки',
    'Sex' => 'Пол',
    'Timestamp' => 'Дата / Время',
    'Update Member: {0}' => 'Обновить участника: {0}',
    'Update Party: {0}' => 'Обновить встречу: {0}',
    'Update Place: {0}' => 'Обновить место: {0}',
    'Update Price: {0}' => 'Обновить стоимость: {0}',
    'Updated At' => 'Обновлено',
    'Visited' => 'Посетил',
    '{0} year' => '{0} год',
    '{0} years' => '{0} года',
    '{0} ages' => '{0} лет',
];
