<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Asks' => 'Заявки',
    'Confirmed' => 'Записан',
    'Create Ask' => 'Создать заявку',
    'ID' => '',
    'Member ID' => '',
    'Party ID' => '',
    'Place ID' => '',
    'Price ID' => '',
    'Processed' => 'Обработан',
    'Update Ask: {0}' => 'Обновить заявку: {0}',
    'User ID' => '',
    'Address' => 'Адрес',
    'Admin Panel' => 'Панель Администратора',
    'Age' => 'Возраст',
    'Base' => 'Базовая',
    'Company' => 'Групповая',
    'Create Member' => 'Создать участника',
    'Create Party' => 'Создать встречу',
    'Create Place' => 'Создать место',
    'Create Price' => 'Создать расценки',
    'Created At' => 'Создан От',
    'Description' => 'Описание',
    'Dob' => 'День рождения',
    'English' => 'Английский',
    'Is Default' => 'По умолчанию',
    'Landing' => 'Лэндинг',
    'Map' => 'Карта',
    'Members' => 'Участники',
    'Name' => 'Имя',
    'Max Members' => 'Предел участников',
    'Paid' => 'Оплачено',
    'Parties' => 'Встречи',
    'Phone' => 'Телефон',
    'Photo' => 'Фото',
    'Places' => 'Места',
    'Prices' => 'Расценки',
    'Remember Me' => 'Запомнить',
    'Repeat' => 'Повторная',
    'Resume' => 'Продолжить',
    'Russian' => 'Русский',
    'Sex' => 'Пол',
    'Timestamp' => 'Время',
    'Update Member: {0}' => 'Обновить участника: {0}',
    'Update Party: {0}' => 'Обновить встречу: {0}',
    'Update Place: {0}' => 'Обновить место: {0}',
    'Update Price: {0}' => 'Обновить стоимость: {0}',
    'Updated At' => 'Обновлен От',
    'Visited' => 'Посетил',
];
