<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Accept All' => 'Подтвердить все',
    'Accept Ask' => 'Выписать билет',
    'Admin' => 'Админ',
    'Admin Panel' => 'Панель Администратора',
    'Age Groups' => 'Группы предпочтения',
    'All asks accepted successful!' => 'Все заявки успешно подтверждены!',
    'Are you sure you want to accept all asks?' => 'Вы уверены, что хотите подтвердить все заявки?',
    'Are you sure you want to reject all asks?' => 'Вы уверены, что хотите отклонить все заявки?',
    'Ask accepted successful!' => 'Заявка успешно подтверждена!',
    'Asks' => 'Заявки',
    'Control' => 'Контроль',
    'Create Ask' => 'Создать заявку',
    'Create Group' => 'Создать группу',
    'Create Member' => 'Создать участника',
    'Create Party' => 'Создать встречу',
    'Create Place' => 'Создать место',
    'Create Price' => 'Создать расценки',
    'Create Setting' => 'Создать настройку',
    'Create Ticket' => 'Создать билет',
    'Date filter' => 'Фильтр даты',
    'Groups' => 'Группы',
    'Irrelevant' => 'Не имеет значения',
    'Manager' => 'Менеджер',
    'Map Constructor' => 'Конструктор карт',
    'Media' => 'Медиа',
    'Member' => 'Участник',
    'Member Save' => 'Сохранить участника',
    'Member Update' => 'Обновить участника',
    'Member saved successful!' => 'Участник успешно сохранен!',
    'Members' => 'Участники',
    'My age' => 'Моего возраста',
    'Older than me' => 'Старше меня',
    'OneLove CRM' => '',
    'Open all asks' => 'Открыть все заявки',
    'Operator' => 'Оператор',
    'Parties' => 'Встречи',
    'Party' => 'Встреча',
    'Place' => 'Место',
    'Places' => 'Места',
    'Price' => 'Стоимость',
    'Prices' => 'Расценки',
    'Reject All' => 'Отклонить все',
    'Select ask member' => 'Выберите участника заявки',
    'Select asked party' => 'Выберите запрашиваемую встречу',
    'Select party date and time' => 'Выберите дату и время встречи',
    'Select user account' => 'Выберите аккаунт',
    'Select your day of birth' => 'Выберите день рождения',
    'Setting' => 'Настройка',
    'Settings' => 'Настройки',
    'Tickets' => 'Билеты',
    'Update Ask: {0}' => 'Обновить заявку: {0}',
    'Update Group: {0}' => 'Обновить группу: {0}',
    'Update Member: {0}' => 'Обновить участника: {0}',
    'Update Party: {0}' => 'Обновить встречу: {0}',
    'Update Place: {0}' => 'Обновить место: {0}',
    'Update Price: {0}' => 'Обновить стоимость: {0}',
    'Update Setting: {name}' => 'Обновить настройку',
    'Update Ticket: {name}' => 'Обновить билет: {name}',
    'View Ask' => 'Показать заявку',
    'Welcome to Party Management System!' => 'Welcome to Party Management System!',
    'Younger than me' => 'Младше меня',
];
