<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Accept All' => 'Подтвердить все',
    'Accept Ask' => 'Выписать билет',
    'Admin' => 'Админ',
    'Admin Panel' => 'Панель Администратора',
    'Age Groups' => 'Группы предпочтения',
    'All asks accepted successful!' => 'Все заявки успешно подтверждены!',
    'Are you sure you want to accept all asks?' => 'Вы уверены, что хотите подтвердить все заявки?',
    'Are you sure you want to reject all asks?' => 'Вы уверены, что хотите отклонить все заявки?',
    'Ask accepted successful!' => 'Заявка успешно подтверждена!',
    'Asks' => 'Заявки',
    'Ask Make' => 'Заявок',
    'Ask Reject' => 'Отклонено',
    'Ask Member' => 'Участников',
    'Ask Accept' => 'Приглашений',
    'Make Ask'   => 'Добавить заявку',
    'Reject Ask' => 'Отклонить заявку',
    'Party Close' => 'Встреч',
    'Ticket Close' => 'Билетов',
    'Member Visit' => 'Посетило',
    'Member Pay' => 'Заплатили',
    'Control' => 'Контроль',
    'Create Statistic' => 'Создать статистику',
    'Create Ask' => 'Создать заявку',
    'Create Group' => 'Создать группу',
    'Create Member' => 'Создать участника',
    'Create Party' => 'Создать встречу',
    'Create Place' => 'Создать место',
    'Create Price' => 'Создать расценки',
    'Create Setting' => 'Создать настройку',
    'Create Ticket' => 'Создать билет',
    'Search Statistic' => 'Подсчитать',
    'Dashboard' => 'Доска',
    'Date' => 'Дата',
    'Date filter' => 'Фильтр даты',
    'Groups' => 'Группы',
    'Manager' => 'Менеджер',
    'From' => 'Начиная от...',
    'To'   => 'Заканчивая до...',
    'Map Constructor' => 'Конструктор карт',
    'Media' => 'Медиа',
    'Member' => 'Участник',
    'Member Save' => 'Сохранить участника',
    'Member Update' => 'Обновить участника',
    'Member saved successful!' => 'Участник успешно сохранен!',
    'Members' => 'Участники',
    'Invalid time range!' => 'Неверный временной диапазон!',
    'Here is the information needed for the operator to work.'
        => 'Здесь находится вся информация, необходимая для работы оператора',
    'OneLove CRM' => '',
    'Open all asks' => 'Открыть все заявки',
    'Operator' => 'Оператор',
    'Operator Panel' => 'Доска оператора',
    'Parties' => 'Встречи',
    'Party' => 'Встреча',
    'Place' => 'Место',
    'Places' => 'Места',
    'Price' => 'Стоимость',
    'Prices' => 'Расценки',
    'Reject All' => 'Отклонить все',
    'Statistics' => 'Статистика',
    'Group By'  => 'Сгрупировать по:',
    'Operators filter' => 'Отфильтровать по операторам:',
    'Dates' => 'Даты',
    'Weeks' => 'Недели',
    'Months' => 'Месяцы',
    'Total:' => 'Всего:',
    'Views' => 'Просмотры',
    'Desktop Views' => 'Компьютер',
    'Mobile Views' => 'Мобильный',
    'Select operators...' => 'Выберите операторов...',
    'Select ask member' => 'Выберите участника заявки',
    'Select asked party' => 'Выберите запрашиваемую встречу',
    'Select party date and time' => 'Выберите дату и время встречи',
    'Select user account' => 'Выберите аккаунт',
    'Select your day of birth' => 'Выберите день рождения',
    'Setting' => 'Настройка',
    'Settings' => 'Настройки',
    'Tickets' => 'Билеты',
    'Update Ask: {0}' => 'Обновить заявку: {0}',
    'Update Group: {0}' => 'Обновить группу: {0}',
    'Update Member: {0}' => 'Обновить участника: {0}',
    'Update Party: {0}' => 'Обновить встречу: {0}',
    'Update Place: {0}' => 'Обновить место: {0}',
    'Update Price: {0}' => 'Обновить стоимость: {0}',
    'Update Setting: {name}' => 'Обновить настройку',
    'Update Statistic: {name}' => 'Обновить статистику: {name}',
    'Update Ticket: {name}' => 'Обновить билет: {name}',
    'View Ask' => 'Показать заявку',
    'Welcome to Party Management System!' => 'Добро пожаловать в систему управления встречами!',
    'How many views of the offer per time was received from desktop and mobile phone'
        => 'Сколько просмотров предложения за выбранное время было получено с компьютера и мобильного телефона',
    'How many asks per time was making, accepted, rejected or saved'
        => 'Сколько заявок за выбранное время было сделано, принято, отклонено или сохранено как участник',
    'How many parties per time was closed, how many tickets per time was closed'
        => 'Сколько вечеринок за выбранное время было проведено и сколько билетов за выбранное время было закрыто',
    'How many members per time was visited parties, how much members per time was paid'
        => 'Сколько участников за выбранное время посетили вечеринки и сколько они заплатили'
];
