<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => 'Адрес',
    'Age' => 'Возраст',
    'Age Group' => 'Группа предпочтения',
    'Base' => 'Базовая',
    'Call' => 'Позвонить',
    'Cannot delete default!' => 'Нельзя удалить элемент по умолчанию!',
    'Closed' => 'Закрыто',
    'Company' => 'Групповая',
    'Created At' => 'Создано',
    'Day of Birth' => 'День рождения',
    'Description' => 'Описание',
    'Female' => 'Женский',
    'Group' => 'Группа',
    'ID' => '',
    'Is Blocked' => 'Блокировано',
    'Is Default' => 'По умолчанию',
    'Key' => 'Программный ключ',
    'Label' => 'Название',
    'Male' => 'Мужской',
    'Map' => 'Карта',
    'Max Members' => 'Предел участников',
    'Member' => 'Участник',
    'Member Resume' => 'О себе',
    'Name' => 'Имя',
    'No present' => 'Не указано',
    'Operator' => 'Оператор',
    'Operator Comment' => 'Комментарий оператора',
    'Operator Phone' => 'Телефон оператора',
    'Operators' => 'Операторы для рассылки',
    'Paid' => 'Оплачено',
    'Party' => 'Встреча',
    'Party Name' => 'Название',
    'Phone' => 'Телефон',
    'Phone should contain {0} numbers' => 'Телефон должен содеражать все {0} цифр',
    'Photo' => 'Фото',
    'Place' => 'Место',
    'Place Name' => 'Название',
    'Price' => 'Расценки',
    'Repeat' => 'Повторная',
    'Rule' => 'Правило',
    'Sex' => 'Пол',
    'Ticket for this party and for this member already exist!' => 'Билет для этого участника этой встречи уже существует!',
    'Timestamp' => 'Дата / Время',
    'Updated At' => 'Обновлено',
    'Updated By' => 'Обновил',
    'User' => 'Аккаунт',
    'Value' => 'Значение',
    'Visited' => 'Посетил',
    '{0} ages' => '{0} лет',
    '{0} guests' => '{0} гостей',
    '{0} year' => '{0} год',
    '{0} years' => '{0} года',
];
