<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Admin' => 'Администратор',
    'Asks' => 'Заявки',
    'Accept All' => 'Подтвердить все',
    'Accept Ask' => 'Подтвердить заявку',
    'Ask accepted successful!' => 'Заявка успешно подтверждена!',
    'All asks accepted successful!' => 'Все заявки успешно подтверждены!',
    'Reject All' => 'Отклонить все',
    'Are you sure you want to reject all asks?'
        => 'Вы уверены, что хотите отклонить все заявки?',
    'Are you sure you want to accept all asks?'
        => 'Вы уверены, что хотите подтвердить все заявки?',
    'Ask sent' => 'Заявка отправлена',
    'Control' => 'Контроль',
    'Confirmed' => 'Записан',
    'Create Ask' => 'Создать заявку',
    'ID' => '',
    'Is Blocked' => 'Блокировано',
    'Invalid characters in name.' => 'Недопустимый формат имени',
    'Panel' => 'Панель',
    'Party' => 'Встреча',
    'Place' => 'Место',
    'Price' => 'Расценки',
    'Processed' => 'Обработана',
    'Phone should contain {0} numbers' => 'Телефон должен содеражать все {0} цифр',
    'Update Ask: {0}' => 'Обновить заявку: {0}',
    'User' => 'Аккаунт',
    'Address' => 'Адрес',
    'Admin Panel' => 'Панель Администратора',
    'Age' => 'Возраст',
    'Base' => 'Базовая',
    'Female' => 'Женский',
    'Cannot delete default!' => 'Нельзя удалить элемент по умолчанию!',
    'Company' => 'Групповая',
    'Comment' => 'Комментарий',
    'Closed' => 'Закрыто',
    'Create Member' => 'Создать участника',
    'Create Setting' => 'Создать настройку',
    'Create Party' => 'Создать встречу',
    'Create Place' => 'Создать место',
    'Create Price' => 'Создать расценки',
    'Create Ticket' => 'Создать билет',
    'Created At' => 'Создано',
    'Description' => 'Описание',
    'Day of Birth' => 'День рождения',
    'English' => 'Английский',
    'Is Default' => 'По умолчанию',
    'Fail' => 'Очень жаль!',
    'Something went wrong. Please try later.'
        => 'Что-то пошло не так... Пожалуйтса, попробуйте чуть позже!',
    'Key'   => 'Программный ключ',
    'Value'   => 'Значение',
    'Label' => 'Название',
    'Landing' => 'Лэндинг',
    'Male' => 'Мужской',
    'Manager' => 'Менеджер',
    'Map' => 'Карта',
    'Map Constructor' => 'Конструктор карт',
    'Max Members' => 'Предел участников',
    'Member' => 'Участник',
    'Members' => 'Участники',
    'Name' => 'Имя',
    'New party ask!' => 'Новая заявка на участие!',
    'New call request!' => 'Запрос на обратный звонок!',
    'No' => 'Нет',
    'Operator' => 'Оператор',
    'Open all asks' => 'Открыть все заявки',
    'Operator Phone' => 'Телефон оператора',
    'Our operator will contact you shortly.' => 'Наш оператор свяжется с Вами в ближайшее время.',
    'Operators' => 'Операторы для рассылки',
    'Paid' => 'Оплачено',
    'Party Name' => 'Название',
    'Place Name' => 'Название',
    'Parties' => 'Встречи',
    'Phone' => 'Телефон',
    'Photo' => 'Фото',
    'Places' => 'Места',
    'Prices' => 'Расценки',
    'Remember Me' => 'Запомнить',
    'Repeat' => 'Повторная',
    'Member Resume' => 'О себе',
    'Russian' => 'Русский',
    'Send Ask' => 'Записаться',
    'Setting'   => 'Настройка',
    'Settings' => 'Настройки',
    'Success' => 'Отлично!',
    'Select asked party' => 'Выберите запрашиваемую встречу',
    'Select ask member' => 'Выберите участника заявки',
    'Sex' => 'Пол',
    'Ticket' => 'Билет',
    'Tickets' => 'Билеты',
    'Timestamp' => 'Дата / Время',
    'Updated By'    => 'Обновил',
    'Update Ticket: {0}' => 'Обновить билет: {0}',
    'Update Member: {0}' => 'Обновить участника: {0}',
    'Update Party: {0}' => 'Обновить встречу: {0}',
    'Update Place: {0}' => 'Обновить место: {0}',
    'Update Price: {0}' => 'Обновить стоимость: {0}',
    'Updated At' => 'Обновлено',
    'Visited' => 'Посетил',
    '{0} year' => '{0} год',
    '{0} years' => '{0} года',
    '{0} ages' => '{0} лет',
    '{0} guests' => '{0} гостей'
];
