<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assignments have been updated' => '',
    'Auth item with such name already exists' => '',
    'Children' => '',
    'Class' => '',
    'Class "{0}" does not exist' => '',
    'Create' => '',
    'Create new permission' => '',
    'Create new role' => '',
    'Create rule' => '',
    'Created at' => '',
    'Data cannot be decoded' => '',
    'Data must be type of JSON ({0})' => '',
    'Description' => '',
    'Enter the description' => '',
    'Invalid value' => '',
    'Item has been created' => '',
    'Item has been updated' => '',
    'Items' => '',
    'Name' => '',
    'Name is already in use' => '',
    'New permission' => '',
    'New role' => '',
    'New rule' => '',
    'New user' => '',
    'Not found' => '',
    'Permissions' => '',
    'Roles' => '',
    'Rule' => '',
    'Rule class can not be instantiated' => '',
    'Rule class must extend "yiibacRule"' => '',
    'Rule has been added' => '',
    'Rule has been removed' => '',
    'Rule has been updated' => '',
    'Rule name' => '',
    'Rule {0} does not exist' => '',
    'Rules' => '',
    'Save' => '',
    'Select permission' => '',
    'Select role' => '',
    'Select rule' => '',
    'There is neither role nor permission with name "{0}"' => '',
    'Update assignments' => '',
    'Update permission' => '',
    'Update role' => '',
    'Update rule' => '',
    'Updated at' => '',
    'Users' => '',
];
